"""'add_video'

Revision ID: 04a7888f8f0e
Revises: 42ebdef06e74
Create Date: 2020-03-26 02:27:55.716204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a7888f8f0e'
down_revision = '42ebdef06e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Series',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SEid', sa.String(length=64), nullable=False),
    sa.Column('SEname', sa.String(length=255), nullable=True),
    sa.Column('DOid', sa.String(length=64), nullable=True),
    sa.Column('SEsort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('SEid')
    )
    op.create_table('Video',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('VIid', sa.String(length=64), nullable=False),
    sa.Column('VImedia', sa.Text(), nullable=True),
    sa.Column('VIname', sa.String(length=255), nullable=True),
    sa.Column('VIthumbnail', sa.Text(), nullable=True),
    sa.Column('SEid', sa.String(length=64), nullable=True),
    sa.Column('DOid', sa.String(length=64), nullable=True),
    sa.Column('VIdur', sa.String(length=64), nullable=True),
    sa.Column('VIsort', sa.Integer(), nullable=True),
    sa.Column('VIbriefIntroduction', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('VIid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Video')
    op.drop_table('Series')
    # ### end Alembic commands ###
