"""'add'

Revision ID: 0c27c91931bb
Revises: d2d6da5612bd
Create Date: 2020-04-11 15:25:24.016343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c27c91931bb'
down_revision = 'd2d6da5612bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('OrderMain', 'PRid',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               nullable=True)
    op.alter_column('OrderMain', 'PRprice',
               existing_type=mysql.DECIMAL(precision=28, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('OrderMain', 'PRprice',
               existing_type=mysql.DECIMAL(precision=28, scale=2),
               nullable=False)
    op.alter_column('OrderMain', 'PRid',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               nullable=False)
    # ### end Alembic commands ###
