"""'add'

Revision ID: 2e689868d8dd
Revises: 8166c625612d
Create Date: 2020-12-27 03:36:04.607992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e689868d8dd'
down_revision = '8166c625612d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SharingParameters',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SPSid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('SPScontent', sa.Text(), nullable=True),
    sa.Column('SPSname', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('SPSid')
    )
    op.add_column('Answer', sa.Column('EVshare', sa.Text(), nullable=True))
    op.add_column('EvaluationPoint', sa.Column('DOid', sa.String(length=64), nullable=True))
    op.add_column('EvaluationPoint', sa.Column('EPanalysis', sa.String(length=64), nullable=True))
    op.add_column('EvaluationPoint', sa.Column('EPaward', sa.String(length=64), nullable=True))
    op.add_column('EvaluationPoint', sa.Column('EPevaluation', sa.Text(), nullable=True))
    op.add_column('EvaluationPoint', sa.Column('EPshareLevel', sa.Integer(), nullable=True))
    op.add_column('EvaluationPoint', sa.Column('EPshareWords', sa.Text(), nullable=True))
    op.add_column('EvaluationPoint', sa.Column('EPtitle', sa.String(length=64), nullable=True))
    op.alter_column('OrderMain', 'isdelete',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.add_column('Products', sa.Column('DEid', sa.String(length=64), nullable=True))
    op.add_column('User', sa.Column('USwxac', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'USwxac')
    op.drop_column('Products', 'DEid')
    op.alter_column('OrderMain', 'isdelete',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_column('EvaluationPoint', 'EPtitle')
    op.drop_column('EvaluationPoint', 'EPshareWords')
    op.drop_column('EvaluationPoint', 'EPshareLevel')
    op.drop_column('EvaluationPoint', 'EPevaluation')
    op.drop_column('EvaluationPoint', 'EPaward')
    op.drop_column('EvaluationPoint', 'EPanalysis')
    op.drop_column('EvaluationPoint', 'DOid')
    op.drop_column('Answer', 'EVshare')
    op.drop_table('SharingParameters')
    # ### end Alembic commands ###
