"""'uitrue'

Revision ID: 3c2feedbe813
Revises: cb53b24eb2a5
Create Date: 2020-04-04 01:57:30.479517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c2feedbe813'
down_revision = 'cb53b24eb2a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserIntegral', sa.Column('UItrue', sa.Integer(), nullable=True, comment='是否领取 0 未领取 1已领取'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserIntegral', 'UItrue')
    # ### end Alembic commands ###
