"""user_add_gender

Revision ID: 403626b2f4a2
Revises: e8db55d71fbf
Create Date: 2020-03-20 23:45:09.234871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '403626b2f4a2'
down_revision = 'e8db55d71fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Example', 'EXaddr',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=256),
               comment='来历',
               existing_nullable=True)
    op.alter_column('Example', 'EXage',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=8),
               comment='年龄',
               existing_nullable=True)
    op.alter_column('Example', 'EXalpha',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment='主图',
               existing_nullable=True)
    op.alter_column('Example', 'EXbriefIntroduction',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment='简介',
               existing_nullable=True)
    op.alter_column('Example', 'EXcaseAnalysis',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment='案例分析',
               existing_nullable=True)
    op.alter_column('Example', 'EXchiefComplaint',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment='主诉',
               existing_nullable=True)
    op.alter_column('Example', 'EXclinicVisitHistory',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment='就诊史',
               existing_nullable=True)
    op.alter_column('Example', 'EXdiagnosis',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment='诊断',
               existing_nullable=True)
    op.alter_column('Example', 'EXgender',
               existing_type=mysql.INTEGER(display_width=11),
               comment='性别 {0： man，1：woman}',
               existing_nullable=True)
    op.alter_column('Example', 'EXheight',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=8),
               comment='身高',
               existing_nullable=True)
    op.alter_column('Example', 'EXinspectionResults',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment='校验结果',
               existing_nullable=True)
    op.alter_column('Example', 'EXname',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=255),
               comment='患者姓名',
               existing_nullable=True)
    op.alter_column('Example', 'EXperoration',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment='结束语',
               existing_nullable=True)
    op.alter_column('Example', 'EXsort',
               existing_type=mysql.INTEGER(display_width=11),
               comment='排序',
               existing_nullable=True)
    op.alter_column('Example', 'EXtreated',
               existing_type=mysql.DATETIME(),
               comment='就诊时间',
               existing_nullable=True)
    op.alter_column('Example', 'EXtreatmentOutcome',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment='治疗结果',
               existing_nullable=True)
    op.alter_column('Example', 'EXtreatmentPrinciple',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment='治疗原则',
               existing_nullable=True)
    op.alter_column('Example', 'EXweight',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=8),
               comment='体重',
               existing_nullable=True)
    op.alter_column('Example', 'SYid',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               comment='症状ID',
               existing_nullable=True)
    op.alter_column('Example', 'createtime',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('Example', 'isdelete',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否删除',
               existing_nullable=True)
    op.alter_column('Example', 'updatetime',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=True)
    op.add_column('Family', sa.Column('FAself', sa.Boolean(), nullable=True, comment='是否是本人'))
    op.alter_column('Family', 'FAgender',
               existing_type=mysql.INTEGER(display_width=11),
               comment='性别 {0: unknown 1：male，2：female}',
               existing_comment='性别 {0： man，1：woman}',
               existing_nullable=True)
    op.add_column('User', sa.Column('USgender', sa.Integer(), nullable=True, comment='性别 {0: unknown 1：male，2：female}'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'USgender')
    op.alter_column('Family', 'FAgender',
               existing_type=mysql.INTEGER(display_width=11),
               comment='性别 {0： man，1：woman}',
               existing_comment='性别 {0: unknown 1：male，2：female}',
               existing_nullable=True)
    op.drop_column('Family', 'FAself')
    op.alter_column('Example', 'updatetime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('Example', 'isdelete',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否删除',
               existing_nullable=True)
    op.alter_column('Example', 'createtime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('Example', 'SYid',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               comment=None,
               existing_comment='症状ID',
               existing_nullable=True)
    op.alter_column('Example', 'EXweight',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=8),
               comment=None,
               existing_comment='体重',
               existing_nullable=True)
    op.alter_column('Example', 'EXtreatmentPrinciple',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment=None,
               existing_comment='治疗原则',
               existing_nullable=True)
    op.alter_column('Example', 'EXtreatmentOutcome',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment=None,
               existing_comment='治疗结果',
               existing_nullable=True)
    op.alter_column('Example', 'EXtreated',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='就诊时间',
               existing_nullable=True)
    op.alter_column('Example', 'EXsort',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='排序',
               existing_nullable=True)
    op.alter_column('Example', 'EXperoration',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment=None,
               existing_comment='结束语',
               existing_nullable=True)
    op.alter_column('Example', 'EXname',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=255),
               comment=None,
               existing_comment='患者姓名',
               existing_nullable=True)
    op.alter_column('Example', 'EXinspectionResults',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment=None,
               existing_comment='校验结果',
               existing_nullable=True)
    op.alter_column('Example', 'EXheight',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=8),
               comment=None,
               existing_comment='身高',
               existing_nullable=True)
    op.alter_column('Example', 'EXgender',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='性别 {0： man，1：woman}',
               existing_nullable=True)
    op.alter_column('Example', 'EXdiagnosis',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment=None,
               existing_comment='诊断',
               existing_nullable=True)
    op.alter_column('Example', 'EXclinicVisitHistory',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment=None,
               existing_comment='就诊史',
               existing_nullable=True)
    op.alter_column('Example', 'EXchiefComplaint',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment=None,
               existing_comment='主诉',
               existing_nullable=True)
    op.alter_column('Example', 'EXcaseAnalysis',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment=None,
               existing_comment='案例分析',
               existing_nullable=True)
    op.alter_column('Example', 'EXbriefIntroduction',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment=None,
               existing_comment='简介',
               existing_nullable=True)
    op.alter_column('Example', 'EXalpha',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment=None,
               existing_comment='主图',
               existing_nullable=True)
    op.alter_column('Example', 'EXage',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=8),
               comment=None,
               existing_comment='年龄',
               existing_nullable=True)
    op.alter_column('Example', 'EXaddr',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=256),
               comment=None,
               existing_comment='来历',
               existing_nullable=True)
    # ### end Alembic commands ###
