"""user_model

Revision ID: 49a2c592b25b
Revises: b8ea3b6eb406
Create Date: 2020-03-16 02:20:01.536812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49a2c592b25b'
down_revision = 'b8ea3b6eb406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AddressArea',
    sa.Column('isdelete', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('AAid', sa.String(length=8), nullable=False, comment='区县id'),
    sa.Column('AAname', sa.String(length=32), nullable=False, comment='区县名'),
    sa.Column('ACid', sa.String(length=8), nullable=False, comment='市名'),
    sa.PrimaryKeyConstraint('AAid')
    )
    op.create_table('AddressCity',
    sa.Column('isdelete', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('ACid', sa.String(length=8), nullable=False, comment='市id'),
    sa.Column('ACname', sa.String(length=20), nullable=False, comment='市名'),
    sa.Column('APid', sa.String(length=8), nullable=False, comment='省id'),
    sa.PrimaryKeyConstraint('ACid')
    )
    op.create_table('AddressProvince',
    sa.Column('isdelete', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('APid', sa.String(length=8), nullable=False, comment='省id'),
    sa.Column('APname', sa.String(length=20), nullable=False, comment='省名'),
    sa.PrimaryKeyConstraint('APid')
    )
    op.create_table('Family',
    sa.Column('isdelete', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('FAid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True, comment='用户ID'),
    sa.Column('FAtype', sa.Integer(), nullable=True, comment='家人类型 0 孩子，1 父亲，2 母亲'),
    sa.Column('FAname', sa.String(length=255), nullable=True, comment='家人姓名'),
    sa.Column('FAage', sa.Integer(), nullable=True, comment='家人年龄'),
    sa.Column('FAidentification', sa.String(length=18), nullable=True, comment='身份证号'),
    sa.Column('FAtel', sa.String(length=13), nullable=True, comment='手机号'),
    sa.Column('FAgender', sa.Integer(), nullable=True, comment='性别 {0： man，1：woman}'),
    sa.Column('AAid', sa.String(length=64), nullable=True, comment='居住地区域ID'),
    sa.Column('FAaddress', sa.Text(), nullable=True, comment='家人居住地'),
    sa.PrimaryKeyConstraint('FAid')
    )
    op.create_table('User',
    sa.Column('isdelete', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('USname', sa.String(length=255), nullable=False, comment='用户名'),
    sa.Column('USavatar', sa.Text(), nullable=True, comment='用户头像'),
    sa.Column('USlevel', sa.Integer(), nullable=True, comment='vip等级'),
    sa.Column('USintegral', sa.Integer(), nullable=True, comment='用户积分'),
    sa.Column('USopenid', sa.Text(), nullable=True, comment='小程序 openid'),
    sa.Column('USunionid', sa.Text(), nullable=True, comment='统一 unionID'),
    sa.PrimaryKeyConstraint('USid')
    )
    op.create_table('UserAddress',
    sa.Column('isdelete', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('UAid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True, comment='用户id'),
    sa.Column('UAname', sa.String(length=16), nullable=False, comment='收货人姓名'),
    sa.Column('UAtel', sa.String(length=16), nullable=False, comment='收货人电话'),
    sa.Column('UAtext', sa.String(length=255), nullable=False, comment='具体地址'),
    sa.Column('UAdefault', sa.Boolean(), nullable=True, comment='默认收货地址'),
    sa.Column('AAid', sa.String(length=8), nullable=False, comment='关联的区域id'),
    sa.PrimaryKeyConstraint('UAid')
    )
    op.alter_column('Departments', 'DEalpha',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment='科室主图',
               existing_nullable=True)
    op.alter_column('Departments', 'DEicon',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment='科室icon',
               existing_nullable=True)
    op.alter_column('Departments', 'DEicon2',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment='科室icon2',
               existing_nullable=True)
    op.alter_column('Departments', 'DEintroduction',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment='科室介绍',
               existing_nullable=True)
    op.alter_column('Departments', 'DEname',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=255),
               comment='科室名',
               existing_nullable=False)
    op.alter_column('Departments', 'DEsort',
               existing_type=mysql.INTEGER(display_width=11),
               comment='科室排序',
               existing_nullable=True)
    op.alter_column('Departments', 'createtime',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('Departments', 'isdelete',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否删除',
               existing_nullable=True)
    op.alter_column('Departments', 'updatetime',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=True)
    op.alter_column('Doctor', 'DEid',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               comment='科室id',
               existing_nullable=True)
    op.alter_column('Doctor', 'DOdetails',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment='医生简介',
               existing_nullable=True)
    op.alter_column('Doctor', 'DOname',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=255),
               comment='医生名',
               existing_nullable=False)
    op.alter_column('Doctor', 'DOpassword',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=255),
               comment='医生登录密码',
               existing_nullable=True)
    op.alter_column('Doctor', 'DOskilledIn',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment='擅长方向',
               existing_nullable=True)
    op.alter_column('Doctor', 'DOsort',
               existing_type=mysql.INTEGER(display_width=11),
               comment='科室医生排序',
               existing_nullable=True)
    op.alter_column('Doctor', 'DOtel',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=13),
               comment='医生电话',
               existing_nullable=True)
    op.alter_column('Doctor', 'DOtitle',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=255),
               comment='医生职称',
               existing_nullable=True)
    op.alter_column('Doctor', 'DOwxid',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=255),
               comment='微信ID',
               existing_nullable=True)
    op.alter_column('Doctor', 'createtime',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('Doctor', 'isdelete',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否删除',
               existing_nullable=True)
    op.alter_column('Doctor', 'updatetime',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=True)
    op.alter_column('DoctorMedia', 'DMmedia',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment='图片链接',
               existing_nullable=True)
    op.alter_column('DoctorMedia', 'DMsort',
               existing_type=mysql.INTEGER(display_width=11),
               comment='图片顺序',
               existing_nullable=True)
    op.alter_column('DoctorMedia', 'DMtype',
               existing_type=mysql.INTEGER(display_width=11),
               comment='0 医生主图 1 医生列表图 2 医生二维码',
               existing_nullable=True)
    op.alter_column('DoctorMedia', 'DOid',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               comment='医生ID',
               existing_nullable=True)
    op.alter_column('DoctorMedia', 'createtime',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('DoctorMedia', 'isdelete',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否删除',
               existing_nullable=True)
    op.alter_column('DoctorMedia', 'updatetime',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=True)
    op.alter_column('Symptom', 'DEid',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               comment='科室id',
               existing_nullable=True)
    op.alter_column('Symptom', 'SYname',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=255),
               comment='症状名',
               existing_nullable=False)
    op.alter_column('Symptom', 'SYsort',
               existing_type=mysql.INTEGER(display_width=11),
               comment='症状排序',
               existing_nullable=True)
    op.alter_column('Symptom', 'createtime',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('Symptom', 'isdelete',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否删除',
               existing_nullable=True)
    op.alter_column('Symptom', 'updatetime',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Symptom', 'updatetime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('Symptom', 'isdelete',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否删除',
               existing_nullable=True)
    op.alter_column('Symptom', 'createtime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('Symptom', 'SYsort',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='症状排序',
               existing_nullable=True)
    op.alter_column('Symptom', 'SYname',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=255),
               comment=None,
               existing_comment='症状名',
               existing_nullable=False)
    op.alter_column('Symptom', 'DEid',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               comment=None,
               existing_comment='科室id',
               existing_nullable=True)
    op.alter_column('DoctorMedia', 'updatetime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('DoctorMedia', 'isdelete',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否删除',
               existing_nullable=True)
    op.alter_column('DoctorMedia', 'createtime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('DoctorMedia', 'DOid',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               comment=None,
               existing_comment='医生ID',
               existing_nullable=True)
    op.alter_column('DoctorMedia', 'DMtype',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='0 医生主图 1 医生列表图 2 医生二维码',
               existing_nullable=True)
    op.alter_column('DoctorMedia', 'DMsort',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='图片顺序',
               existing_nullable=True)
    op.alter_column('DoctorMedia', 'DMmedia',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment=None,
               existing_comment='图片链接',
               existing_nullable=True)
    op.alter_column('Doctor', 'updatetime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('Doctor', 'isdelete',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否删除',
               existing_nullable=True)
    op.alter_column('Doctor', 'createtime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('Doctor', 'DOwxid',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=255),
               comment=None,
               existing_comment='微信ID',
               existing_nullable=True)
    op.alter_column('Doctor', 'DOtitle',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=255),
               comment=None,
               existing_comment='医生职称',
               existing_nullable=True)
    op.alter_column('Doctor', 'DOtel',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=13),
               comment=None,
               existing_comment='医生电话',
               existing_nullable=True)
    op.alter_column('Doctor', 'DOsort',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='科室医生排序',
               existing_nullable=True)
    op.alter_column('Doctor', 'DOskilledIn',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment=None,
               existing_comment='擅长方向',
               existing_nullable=True)
    op.alter_column('Doctor', 'DOpassword',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=255),
               comment=None,
               existing_comment='医生登录密码',
               existing_nullable=True)
    op.alter_column('Doctor', 'DOname',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=255),
               comment=None,
               existing_comment='医生名',
               existing_nullable=False)
    op.alter_column('Doctor', 'DOdetails',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment=None,
               existing_comment='医生简介',
               existing_nullable=True)
    op.alter_column('Doctor', 'DEid',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               comment=None,
               existing_comment='科室id',
               existing_nullable=True)
    op.alter_column('Departments', 'updatetime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('Departments', 'isdelete',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否删除',
               existing_nullable=True)
    op.alter_column('Departments', 'createtime',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('Departments', 'DEsort',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='科室排序',
               existing_nullable=True)
    op.alter_column('Departments', 'DEname',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=255),
               comment=None,
               existing_comment='科室名',
               existing_nullable=False)
    op.alter_column('Departments', 'DEintroduction',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment=None,
               existing_comment='科室介绍',
               existing_nullable=True)
    op.alter_column('Departments', 'DEicon2',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment=None,
               existing_comment='科室icon2',
               existing_nullable=True)
    op.alter_column('Departments', 'DEicon',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment=None,
               existing_comment='科室icon',
               existing_nullable=True)
    op.alter_column('Departments', 'DEalpha',
               existing_type=mysql.TEXT(collation='utf8_bin'),
               comment=None,
               existing_comment='科室主图',
               existing_nullable=True)
    op.drop_table('UserAddress')
    op.drop_table('User')
    op.drop_table('Family')
    op.drop_table('AddressProvince')
    op.drop_table('AddressCity')
    op.drop_table('AddressArea')
    # ### end Alembic commands ###
