"""admin

Revision ID: 4ca0cc5a38bd
Revises: ee986e4e0084
Create Date: 2020-03-13 02:29:53.438084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ca0cc5a38bd'
down_revision = 'ee986e4e0084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Admin', 'ADnum')
    op.drop_column('Admin', 'ADfirstname')
    op.drop_column('Admin', 'ADfirstpwd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Admin', sa.Column('ADfirstpwd', mysql.TEXT(collation='utf8_bin'), nullable=True, comment=' 初始密码 明文保存'))
    op.add_column('Admin', sa.Column('ADfirstname', mysql.TEXT(collation='utf8_bin'), nullable=True, comment=' 初始用户名'))
    op.add_column('Admin', sa.Column('ADnum', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
