"""'review_user'

Revision ID: 50e54c500372
Revises: cc7201084b32
Create Date: 2020-04-02 03:51:38.413524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50e54c500372'
down_revision = 'cc7201084b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Review', sa.Column('USavatar', sa.Text(), nullable=True, comment='用户头像'))
    op.add_column('Review', sa.Column('USname', sa.String(length=255), nullable=True, comment='用户名'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Review', 'USname')
    op.drop_column('Review', 'USavatar')
    # ### end Alembic commands ###
