"""del_FARole

Revision ID: 5294478ae475
Revises: 7ce5bc39e7c5
Create Date: 2020-03-26 03:21:05.026761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5294478ae475'
down_revision = '7ce5bc39e7c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Family', 'FARole')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Family', sa.Column('FARole', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
