"""'update_admin_action'

Revision ID: 5354328e7aa1
Revises: 49a2c592b25b
Create Date: 2020-03-16 22:33:17.030743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5354328e7aa1'
down_revision = '49a2c592b25b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AdminAction', sa.Column('ADtype', sa.String(length=64), nullable=True, comment='管理员类型, {1:超级管理员 2:管理员 3：医生}'))
    op.alter_column('AdminAction', 'AAaction',
               existing_type=mysql.INTEGER(display_width=11),
               comment='管理员行为, {1: 添加, 2: 删除 3: 修改 4:登录}',
               existing_comment='管理员行为, {1: 添加, 2: 删除 3: 修改}',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('AdminAction', 'AAaction',
               existing_type=mysql.INTEGER(display_width=11),
               comment='管理员行为, {1: 添加, 2: 删除 3: 修改}',
               existing_comment='管理员行为, {1: 添加, 2: 删除 3: 修改 4:登录}',
               existing_nullable=True)
    op.drop_column('AdminAction', 'ADtype')
    # ### end Alembic commands ###
