"""'add'

Revision ID: 550e11ef65b8
Revises: f13a01246227
Create Date: 2020-04-11 15:23:08.818827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550e11ef65b8'
down_revision = 'f13a01246227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderMain', sa.Column('PRintegral', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('OrderMain', 'PRintegral')
    # ### end Alembic commands ###
