"""fix_farole

Revision ID: 6b0b5dd55bef
Revises: 5294478ae475
Create Date: 2020-03-26 03:22:03.445392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0b5dd55bef'
down_revision = '5294478ae475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Family', sa.Column('FArole', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Family', 'FArole')
    # ### end Alembic commands ###
