"""'add'

Revision ID: 73eaca760e00
Revises: eadf940c4369
Create Date: 2020-04-04 22:03:09.684893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73eaca760e00'
down_revision = 'eadf940c4369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('CLid', sa.String(length=64), nullable=True))
    op.add_column('products', sa.Column('SMnum', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'SMnum')
    op.drop_column('products', 'CLid')
    # ### end Alembic commands ###
