"""'add_example'

Revision ID: 778d513c8fc9
Revises: 5354328e7aa1
Create Date: 2020-03-18 03:37:02.469583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778d513c8fc9'
down_revision = '5354328e7aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Example',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('EXid', sa.String(length=64), nullable=False),
    sa.Column('SYid', sa.String(length=64), nullable=True),
    sa.Column('EXname', sa.String(length=255), nullable=True),
    sa.Column('EXgender', sa.Integer(), nullable=True),
    sa.Column('EXage', sa.String(length=8), nullable=True),
    sa.Column('EXheight', sa.String(length=8), nullable=True),
    sa.Column('EXweight', sa.String(length=8), nullable=True),
    sa.Column('EXaddr', sa.String(length=256), nullable=True),
    sa.Column('EXtreated', sa.DateTime(), nullable=True),
    sa.Column('EXchiefComplaint', sa.Text(), nullable=True),
    sa.Column('EXclinicVisitHistory', sa.Text(), nullable=True),
    sa.Column('EXcaseAnalysis', sa.Text(), nullable=True),
    sa.Column('EXinspectionResults', sa.Text(), nullable=True),
    sa.Column('EXdiagnosis', sa.Text(), nullable=True),
    sa.Column('EXtreatmentPrinciple', sa.Text(), nullable=True),
    sa.Column('EXtreatmentOutcome', sa.Text(), nullable=True),
    sa.Column('EXperoration', sa.Text(), nullable=True),
    sa.Column('EXbriefIntroduction', sa.Text(), nullable=True),
    sa.Column('EXalpha', sa.Text(), nullable=True),
    sa.Column('EXsort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('EXid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Example')
    # ### end Alembic commands ###
