"""setting_type

Revision ID: 77a59a2aa394
Revises: f1f973c83808
Create Date: 2020-03-13 05:04:34.238132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a59a2aa394'
down_revision = 'f1f973c83808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Setting', sa.Column('STtype', sa.Integer(), nullable=False, comment='{1:客服,2：关于我们}'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Setting', 'STtype')
    # ### end Alembic commands ###
