"""'add'

Revision ID: 7b4640e32d9c
Revises: ea338c8a3d0f
Create Date: 2021-01-13 13:51:04.130918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4640e32d9c'
down_revision = 'ea338c8a3d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Answer', sa.Column('EVpoint', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Answer', 'EVpoint')
    # ### end Alembic commands ###
