"""add_role

Revision ID: 7ce5bc39e7c5
Revises: 04a7888f8f0e
Create Date: 2020-03-26 03:13:46.426051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce5bc39e7c5'
down_revision = '04a7888f8f0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Family', sa.Column('FARole', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Family', 'FARole')
    # ### end Alembic commands ###
