"""identifying_code

Revision ID: 7e062dd060d1
Revises: bece7885db25
Create Date: 2020-03-28 22:23:18.475817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e062dd060d1'
down_revision = 'bece7885db25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('IdentifyingCode',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('ICid', sa.String(length=64), nullable=False),
    sa.Column('ICtelphone', sa.String(length=14), nullable=False),
    sa.Column('ICcode', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('ICid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('IdentifyingCode')
    # ### end Alembic commands ###
