"""user_balance

Revision ID: 8166c625612d
Revises: 4c9147e61ef0
Create Date: 2020-08-07 21:22:09.738209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8166c625612d'
down_revision = '4c9147e61ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WalletRecord',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('WRid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('WRcash', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('WRtype', sa.Integer(), nullable=True),
    sa.Column('ContentId', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('WRid')
    )
    op.add_column('User', sa.Column('USbalance', sa.DECIMAL(precision=28, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'USbalance')
    op.drop_table('WalletRecord')
    # ### end Alembic commands ###
