"""'user_card_phone'

Revision ID: 875805ccd5af
Revises: 946e07fbf5ee
Create Date: 2020-03-20 12:44:11.900021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '875805ccd5af'
down_revision = '946e07fbf5ee'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('User', sa.Column('UScardid', sa.String(length=32), nullable=True, comment='身份证号'))
    op.add_column('User', sa.Column('UStelphone', sa.String(length=16), nullable=True, comment='手机号'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'UStelphone')
    op.drop_column('User', 'UScardid')
    # ### end Alembic commands ###
