"""'doid'

Revision ID: 89a57d813a0f
Revises: 7e062dd060d1
Create Date: 2020-03-29 01:52:36.025826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89a57d813a0f'
down_revision = '7e062dd060d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Subscribe', sa.Column('DOid', sa.String(length=64), nullable=True, comment='医生id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('Subscribe', 'DOid')
    # ### end Alembic commands ###
