"""'classes'

Revision ID: 946e07fbf5ee
Revises: 778d513c8fc9
Create Date: 2020-03-19 22:53:28.192135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '946e07fbf5ee'
down_revision = '778d513c8fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Classes',
    sa.Column('isdelete', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('CLid', sa.String(length=64), nullable=False),
    sa.Column('CLname', sa.String(length=128), nullable=False, comment='课程名称'),
    sa.Column('CLpicture', sa.Text(), nullable=True, comment='课程图'),
    sa.Column('DEid', sa.String(length=64), nullable=True, comment='科室id'),
    sa.Column('DEname', sa.String(length=255), nullable=False, comment='科室名称'),
    sa.Column('CLintroduction', sa.Text(), nullable=True, comment='详细介绍'),
    sa.PrimaryKeyConstraint('CLid')
    )
    op.create_table('Course',
    sa.Column('isdelete', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('COid', sa.String(length=64), nullable=False),
    sa.Column('CLid', sa.String(length=64), nullable=True, comment='课程id'),
    sa.Column('CLname', sa.String(length=128), nullable=True, comment='课程名称'),
    sa.Column('DOid', sa.String(length=64), nullable=True, comment='医生id'),
    sa.Column('DOname', sa.String(length=255), nullable=True, comment='医生名称'),
    sa.Column('COstarttime', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('COendtime', sa.DateTime(), nullable=False, comment='结束时间'),
    sa.Column('COnum', sa.Integer(), nullable=True, comment='限制人数'),
    sa.Column('COstatus', sa.Integer(), nullable=True, comment='课程状态 {101: 未开始 102: 已开始 103：已结束}'),
    sa.PrimaryKeyConstraint('COid')
    )
    op.create_table('Subscribe',
    sa.Column('isdelete', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('SUid', sa.String(length=64), nullable=False),
    sa.Column('COid', sa.String(length=64), nullable=True, comment='排班id'),
    sa.Column('CLname', sa.String(length=128), nullable=True, comment='课程名称'),
    sa.Column('COstarttime', sa.DateTime(), nullable=True, comment='课程开始时间，即预约课程时间'),
    sa.Column('DOname', sa.String(length=255), nullable=True, comment='医生名称'),
    sa.Column('USname', sa.String(length=255), nullable=True, comment='用户名'),
    sa.Column('USid', sa.String(length=64), nullable=True, comment='用户id'),
    sa.Column('UStelphone', sa.String(length=16), nullable=True, comment='用户手机号'),
    sa.Column('SUstatus', sa.Integer(), nullable=True, comment='预约状态{201：已预约，202：已上课，203：已评价}'),
    sa.PrimaryKeyConstraint('SUid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Subscribe')
    op.drop_table('Course')
    op.drop_table('Classes')
    # ### end Alembic commands ###
