"""'einame'

Revision ID: 9f04b8b00d33
Revises: b0bf32ef076a
Create Date: 2020-03-29 19:40:59.555163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f04b8b00d33'
down_revision = 'b0bf32ef076a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AnswerItem', sa.Column('EIname', sa.String(length=128), nullable=False, comment='题目内容'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AnswerItem', 'EIname')
    # ### end Alembic commands ###
