"""admin

Revision ID: a7602f63daf8
Revises: ea1987be79ff
Create Date: 2020-03-12 19:07:20.791927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7602f63daf8'
down_revision = 'ea1987be79ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
