"""user_invitation

Revision ID: b040ab62ef85
Revises: 34ec074ea2ea
Create Date: 2020-04-14 14:07:32.867404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b040ab62ef85'
down_revision = '34ec074ea2ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserInvitation',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UINid', sa.String(length=64), nullable=False),
    sa.Column('USInviter', sa.String(length=64), nullable=True),
    sa.Column('USInvitee', sa.String(length=64), nullable=True),
    sa.Column('UINapi', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('UINid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserInvitation')
    # ### end Alembic commands ###
