"""'pticon'

Revision ID: b0b3b5162488
Revises: 3c2feedbe813
Create Date: 2020-04-04 02:20:56.211655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0b3b5162488'
down_revision = '3c2feedbe813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PointTask', sa.Column('PTicon', sa.Text(), nullable=True, comment='icon'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PointTask', 'PTicon')
    # ### end Alembic commands ###
