"""mofify_icon_type

Revision ID: b8ea3b6eb406
Revises: e8d866bb8195
Create Date: 2020-03-15 03:30:44.091958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ea3b6eb406'
down_revision = 'e8d866bb8195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

