"""'add'

Revision ID: bb07362aaf4c
Revises: 3b92482bf152
Create Date: 2020-03-29 23:33:05.384843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb07362aaf4c'
down_revision = '3b92482bf152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Register',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('REid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('FAid', sa.String(length=64), nullable=True),
    sa.Column('DEid', sa.String(length=64), nullable=True),
    sa.Column('REdate', sa.Date(), nullable=True),
    sa.Column('REamOrPm', sa.Integer(), nullable=True),
    sa.Column('REremarks', sa.Text(), nullable=True),
    sa.Column('REstatus', sa.Integer(), nullable=True),
    sa.Column('REtansferDate', sa.Date(), nullable=True),
    sa.Column('REtansferAmOrPm', sa.Date(), nullable=True),
    sa.Column('REfee', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('REcode', sa.String(length=64), nullable=True),
    sa.Column('DOtel', sa.String(length=13), nullable=True),
    sa.Column('DOname', sa.String(length=255), nullable=True),
    sa.Column('DOmedia', sa.Text(), nullable=True),
    sa.Column('DOtitle', sa.String(length=255), nullable=True),
    sa.Column('DOid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('REid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Register')
    # ### end Alembic commands ###
