"""rename_usintereal_tablename

Revision ID: bece7885db25
Revises: c80a268c9a43
Create Date: 2020-03-27 14:54:53.527775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bece7885db25'
down_revision = 'c80a268c9a43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserIntegral',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UIid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('UIintegral', sa.Integer(), nullable=True),
    sa.Column('UIaction', sa.Integer(), nullable=True),
    sa.Column('UItype', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('UIid')
    )
    op.drop_table('UserSignIn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserSignIn',
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('createtime', mysql.DATETIME(), nullable=True),
    sa.Column('updatetime', mysql.DATETIME(), nullable=True),
    sa.Column('UIid', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('USid', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True),
    sa.Column('UIintegral', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('UIaction', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('UItype', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('UIid'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('UserIntegral')
    # ### end Alembic commands ###
