"""userintegral

Revision ID: c80a268c9a43
Revises: 6b0b5dd55bef
Create Date: 2020-03-27 02:07:28.902690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c80a268c9a43'
down_revision = '6b0b5dd55bef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserSignIn',
    sa.Column('isdelete', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('UIid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True, comment='用户id'),
    sa.Column('UIintegral', sa.Integer(), nullable=True, comment='该动作产生的积分变化数'),
    sa.Column('UIaction', sa.Integer(), nullable=True, comment='积分变动原因'),
    sa.Column('UItype', sa.Integer(), nullable=True, comment='积分变动类型 1 收入 2 支出'),
    sa.PrimaryKeyConstraint('UIid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserSignIn')
    # ### end Alembic commands ###
