"""'review'

Revision ID: cc7201084b32
Revises: cb26e09fd5ce
Create Date: 2020-04-02 03:05:08.355947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc7201084b32'
down_revision = 'cb26e09fd5ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Review',
    sa.Column('isdelete', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('RVid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False, comment='评价人id'),
    sa.Column('RVcontent', sa.Text(), nullable=False, comment='评论内容'),
    sa.Column('DOid', sa.String(length=64), nullable=True, comment='医生id'),
    sa.Column('RVtype', sa.Integer(), nullable=False, comment='401课程， 402挂诊， 403活动， 404案例， 405视频'),
    sa.Column('RVtypeid', sa.String(length=64), nullable=True, comment='关联id'),
    sa.Column('RVnum', sa.DECIMAL(scale=2), nullable=True),
    sa.PrimaryKeyConstraint('RVid')
    )
    op.create_table('ReviewPicture',
    sa.Column('isdelete', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('RPid', sa.String(length=64), nullable=False),
    sa.Column('RVid', sa.String(length=64), nullable=True, comment='评论id'),
    sa.Column('RPpicture', sa.Text(), nullable=True, comment='图片'),
    sa.PrimaryKeyConstraint('RPid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ReviewPicture')
    op.drop_table('Review')
    # ### end Alembic commands ###
