"""'coupon_change'

Revision ID: ce19e637f8f0
Revises: f82fc97eedb7
Create Date: 2020-04-04 00:25:22.233851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce19e637f8f0'
down_revision = 'f82fc97eedb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Coupon',
    sa.Column('isdelete', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('COid', sa.String(length=64), nullable=False),
    sa.Column('COstatus', sa.Integer(), nullable=True, comment='状态501可领取502已结束'),
    sa.Column('COstarttime', sa.DateTime(), nullable=True, comment='有效起始时间'),
    sa.Column('COendtime', sa.DateTime(), nullable=True, comment='有效期结束时间'),
    sa.Column('COdownline', sa.DECIMAL(scale=2), nullable=True, comment='使用最低金额限制,0 为无限制'),
    sa.Column('COsubtration', sa.DECIMAL(scale=2), nullable=True, comment='优惠价格'),
    sa.Column('COlimitnum', sa.Integer(), nullable=True, comment='发放数量'),
    sa.Column('COgetnum', sa.Integer(), nullable=True, comment='已领数量'),
    sa.PrimaryKeyConstraint('COid')
    )
    op.create_table('CouponUser',
    sa.Column('isdelete', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('UCid', sa.String(length=64), nullable=False),
    sa.Column('COid', sa.String(length=64), nullable=False, comment='优惠券id'),
    sa.Column('USid', sa.String(length=64), nullable=False, comment='用户id'),
    sa.Column('COstatus', sa.Integer(), nullable=True, comment='状态501可领取502已结束'),
    sa.Column('COstarttime', sa.DateTime(), nullable=True, comment='有效起始时间'),
    sa.Column('COendtime', sa.DateTime(), nullable=True, comment='有效期结束时间'),
    sa.Column('COdownline', sa.DECIMAL(scale=2), nullable=True, comment='使用最低金额限制,0 为无限制'),
    sa.Column('UCalreadyuse', sa.Integer(), nullable=True, comment='是否已经使用 601已使用602未使用603已过期'),
    sa.PrimaryKeyConstraint('UCid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CouponUser')
    op.drop_table('Coupon')
    # ### end Alembic commands ###
