"""banner

Revision ID: d0ede120be35
Revises: 
Create Date: 2020-03-12 16:40:05.915833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0ede120be35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MiniProgramBanner',
    sa.Column('isdelete', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('BNid', sa.String(length=64), nullable=False),
    sa.Column('ADid', sa.String(length=64), nullable=True, comment='创建者id'),
    sa.Column('BNpicture', sa.Text(), nullable=False, comment='图片'),
    sa.Column('BNsort', sa.Integer(), nullable=True, comment='顺序'),
    sa.Column('contentlink', mysql.LONGTEXT(), nullable=True, comment='跳转链接'),
    sa.PrimaryKeyConstraint('BNid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MiniProgramBanner')
    # ### end Alembic commands ###
