"""add_doctor_and_dep

Revision ID: e8d866bb8195
Revises: f2d1decbf0f9
Create Date: 2020-03-15 01:01:25.451497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d866bb8195'
down_revision = 'f2d1decbf0f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Departments',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('DEid', sa.String(length=64), nullable=False),
    sa.Column('DEname', sa.String(length=255), nullable=False),
    sa.Column('DEalpha', sa.Text(), nullable=True),
    sa.Column('DEsort', sa.Integer(), nullable=True),
    sa.Column('DEintroduction', sa.Text(), nullable=True),
    sa.Column('DEicon', sa.Integer(), nullable=True),
    sa.Column('DEicon2', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('DEid')
    )
    op.create_table('Doctor',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('DOid', sa.String(length=64), nullable=False),
    sa.Column('DOname', sa.String(length=255), nullable=False),
    sa.Column('DOtel', sa.Integer(), nullable=True),
    sa.Column('DOtitle', sa.String(length=255), nullable=True),
    sa.Column('DOdetails', sa.Text(), nullable=True),
    sa.Column('DOwxid', sa.String(length=255), nullable=True),
    sa.Column('DOskilledIn', sa.Text(), nullable=True),
    sa.Column('DOsort', sa.Integer(), nullable=True),
    sa.Column('DOpassword', sa.String(length=255), nullable=True),
    sa.Column('DEid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('DOid')
    )
    op.create_table('DoctorMedia',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('DMid', sa.String(length=64), nullable=False),
    sa.Column('DOid', sa.String(length=64), nullable=True),
    sa.Column('DMtype', sa.Integer(), nullable=True),
    sa.Column('DMmedia', sa.Text(), nullable=True),
    sa.Column('DMsort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('DMid')
    )
    op.create_table('Symptom',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('SYid', sa.String(length=64), nullable=False),
    sa.Column('SYname', sa.String(length=255), nullable=False),
    sa.Column('SYsort', sa.Integer(), nullable=True),
    sa.Column('DEid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('SYid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Symptom')
    op.drop_table('DoctorMedia')
    op.drop_table('Doctor')
    op.drop_table('Departments')
    # ### end Alembic commands ###
