"""'class_index'

Revision ID: e8db55d71fbf
Revises: 875805ccd5af
Create Date: 2020-03-20 13:23:38.522642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8db55d71fbf'
down_revision = '875805ccd5af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Classes', sa.Column('CLindex', sa.Integer(), nullable=True, comment='权重'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Classes', 'CLindex')
    # ### end Alembic commands ###
