"""'add'

Revision ID: ea338c8a3d0f
Revises: 2e689868d8dd
Create Date: 2020-12-29 20:58:20.331530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea338c8a3d0f'
down_revision = '2e689868d8dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EvaluationPoint', sa.Column('DOname', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EvaluationPoint', 'DOname')
    # ### end Alembic commands ###
