"""'add_product'

Revision ID: eadf940c4369
Revises: 09cd9cb88a0d
Create Date: 2020-04-04 20:14:40.748443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eadf940c4369'
down_revision = '09cd9cb88a0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('PRtitle', sa.String(length=255), nullable=True),
    sa.Column('PRtype', sa.Integer(), nullable=True),
    sa.Column('PRmedia', sa.Text(), nullable=True),
    sa.Column('PRstatus', sa.Integer(), nullable=True),
    sa.Column('PRprice', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('PRvipPrice', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('PRintegral', sa.Integer(), nullable=True),
    sa.Column('PRvipIntegral', sa.Integer(), nullable=True),
    sa.Column('PRstock', sa.Integer(), nullable=True),
    sa.Column('COid', sa.String(length=64), nullable=True),
    sa.Column('PRdetails', sa.Text(), nullable=True),
    sa.Column('PRdesc', sa.Text(), nullable=True),
    sa.Column('PRsort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('PRid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
