"""admin

Revision ID: ee986e4e0084
Revises: a7602f63daf8
Create Date: 2020-03-12 19:09:33.526596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee986e4e0084'
down_revision = 'a7602f63daf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('isdelete', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('ADid', sa.String(length=64), nullable=False),
    sa.Column('ADnum', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('ADname', sa.String(length=255), nullable=True, comment='管理员名'),
    sa.Column('ADtelphone', sa.String(length=13), nullable=True, comment='管理员联系电话'),
    sa.Column('ADpassword', sa.Text(), nullable=False, comment='密码'),
    sa.Column('ADfirstpwd', sa.Text(), nullable=True, comment=' 初始密码 明文保存'),
    sa.Column('ADfirstname', sa.Text(), nullable=True, comment=' 初始用户名'),
    sa.Column('ADheader', sa.Text(), nullable=True, comment='头像'),
    sa.Column('ADlevel', sa.Integer(), nullable=True, comment='管理员等级，{1: 超级管理员, 2: 普通管理员'),
    sa.Column('ADstatus', sa.Integer(), nullable=True, comment='账号状态，{0:正常, 1: 被冻结, 2: 已删除}'),
    sa.PrimaryKeyConstraint('ADid')
    )
    op.create_table('AdminAction',
    sa.Column('isdelete', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('AAid', sa.String(length=64), nullable=False),
    sa.Column('ADid', sa.String(length=64), nullable=True, comment='管理员id'),
    sa.Column('AAaction', sa.Integer(), nullable=True, comment='管理员行为, {1: 添加, 2: 删除 3: 修改}'),
    sa.Column('AAmodel', sa.String(length=255), nullable=True, comment='操作的数据表'),
    sa.Column('AAdetail', mysql.LONGTEXT(), nullable=True, comment='请求的data'),
    sa.Column('AAkey', sa.String(length=255), nullable=True, comment='操作数据表的主键的值'),
    sa.PrimaryKeyConstraint('AAid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AdminAction')
    op.drop_table('Admin')
    # ### end Alembic commands ###
