"""'add_order'

Revision ID: f13a01246227
Revises: 73eaca760e00
Create Date: 2020-04-06 10:26:58.263446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f13a01246227'
down_revision = '73eaca760e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OrderMain',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('OMid', sa.String(length=64), nullable=False),
    sa.Column('OMno', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=False),
    sa.Column('OPayno', sa.String(length=64), nullable=True),
    sa.Column('OMmount', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('OMtrueMount', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('OMstatus', sa.Integer(), nullable=True),
    sa.Column('OMrecvPhone', sa.String(length=11), nullable=False),
    sa.Column('OMrecvName', sa.String(length=11), nullable=False),
    sa.Column('OMrecvAddress', sa.Text(), nullable=False),
    sa.Column('OMintegralpayed', sa.Integer(), nullable=True),
    sa.Column('OMintegral', sa.Integer(), nullable=True),
    sa.Column('UCid', sa.String(length=64), nullable=True),
    sa.Column('OMnum', sa.Integer(), nullable=True),
    sa.Column('OMtype', sa.Integer(), nullable=True),
    sa.Column('SMid', sa.String(length=64), nullable=True),
    sa.Column('CLid', sa.String(length=64), nullable=True),
    sa.Column('CLname', sa.String(length=128), nullable=True),
    sa.Column('SMnum', sa.Integer(), nullable=False),
    sa.Column('SMprice', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('PRid', sa.String(length=64), nullable=False),
    sa.Column('PRprice', sa.DECIMAL(precision=28, scale=2), nullable=False),
    sa.Column('PRtitle', sa.String(length=255), nullable=True),
    sa.Column('PRmedia', sa.String(length=255), nullable=True),
    sa.Column('PRcontent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('OMid')
    )
    op.create_table('OrderPay',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('OPayid', sa.String(length=64), nullable=False),
    sa.Column('OPayno', sa.String(length=64), nullable=True),
    sa.Column('OPayType', sa.Integer(), nullable=True),
    sa.Column('OPaytime', sa.DateTime(), nullable=True),
    sa.Column('OPayMount', sa.DECIMAL(precision=28, scale=2), nullable=True),
    sa.Column('OPaysn', sa.String(length=64), nullable=True),
    sa.Column('OPayJson', sa.Text(), nullable=True),
    sa.Column('OPaymarks', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('OPayid')
    )
    op.create_index(op.f('ix_OrderPay_OPayno'), 'OrderPay', ['OPayno'], unique=False)
    op.create_table('UserHour',
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('UHid', sa.String(length=64), nullable=False),
    sa.Column('USid', sa.String(length=64), nullable=True),
    sa.Column('CLid', sa.String(length=64), nullable=True),
    sa.Column('SMnum', sa.Integer(), nullable=True),
    sa.Column('UHnum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('UHid')
    )
    op.add_column('CouponUser', sa.Column('OMid', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CouponUser', 'OMid')
    op.drop_table('UserHour')
    op.drop_index(op.f('ix_OrderPay_OPayno'), table_name='OrderPay')
    op.drop_table('OrderPay')
    op.drop_table('OrderMain')
    # ### end Alembic commands ###
