"""setting

Revision ID: f1f973c83808
Revises: 4ca0cc5a38bd
Create Date: 2020-03-13 04:07:35.444093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1f973c83808'
down_revision = '4ca0cc5a38bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Setting',
    sa.Column('isdelete', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('STid', sa.String(length=64), nullable=False),
    sa.Column('STname', sa.String(length=128), nullable=False),
    sa.Column('STvalue', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('STid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Setting')
    # ### end Alembic commands ###
