"""team and honour

Revision ID: f2d1decbf0f9
Revises: 77a59a2aa394
Create Date: 2020-03-13 05:27:52.125269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d1decbf0f9'
down_revision = '77a59a2aa394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Characteristicteam',
    sa.Column('isdelete', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('CTid', sa.String(length=64), nullable=False),
    sa.Column('CTpicture', sa.Text(), nullable=False, comment='图片'),
    sa.Column('CTname', sa.String(length=128), nullable=False, comment='姓名'),
    sa.Column('CTposition', sa.String(length=128), nullable=False, comment='职位'),
    sa.Column('CToffice', sa.String(length=128), nullable=False, comment='科室'),
    sa.PrimaryKeyConstraint('CTid')
    )
    op.create_table('Honour',
    sa.Column('isdelete', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('HOid', sa.String(length=64), nullable=False),
    sa.Column('HOpicture', sa.Text(), nullable=False, comment='图片'),
    sa.Column('HOtext', sa.Text(), nullable=False, comment='文字'),
    sa.PrimaryKeyConstraint('HOid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Honour')
    op.drop_table('Characteristicteam')
    # ### end Alembic commands ###
