"""'add'

Revision ID: f3d744a663ca
Revises: 7b4640e32d9c
Create Date: 2021-02-21 16:56:30.976506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d744a663ca'
down_revision = '7b4640e32d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Symptom', sa.Column('SYage', sa.String(length=16), nullable=True))
    op.add_column('Symptom', sa.Column('SYattention', sa.Text(), nullable=True))
    op.add_column('Symptom', sa.Column('SYcommon', sa.Text(), nullable=True))
    op.add_column('Symptom', sa.Column('SYdt', sa.String(length=255), nullable=True))
    op.add_column('Symptom', sa.Column('SYreason', sa.Text(), nullable=True))
    op.add_column('Symptom', sa.Column('SYtime', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Symptom', 'SYtime')
    op.drop_column('Symptom', 'SYreason')
    op.drop_column('Symptom', 'SYdt')
    op.drop_column('Symptom', 'SYcommon')
    op.drop_column('Symptom', 'SYattention')
    op.drop_column('Symptom', 'SYage')
    # ### end Alembic commands ###
