from .departments import *
from .config import *
from .admin import *
from .user import *
from .classes import *
from .video import *
from .register import *
from .evaluation import *
from .assistance import *
from .activity import *
from .review import *
from .consultation import *
from .coupon import *
from .products import *