from .departments import *
from .config import *
from .admin import *
from .user import *
from .classes import *
from .video import *
from .register import *
from .evaluation import *
from .assistance import *
